name: deepmass
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1  
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - conda-pack=0.7.1
  - libffi=3.4.2
  - libgomp=13.2.0  
  - libsqlite=3.44.0
  - libzlib=1.2.13
  - openssl=3.1.4
  - pip=23.3.1
  - python=3.8.18
  - tk=8.6.13
  - wheel=0.41.3
  - xz=5.2.6
  - pip:
      - absl-py==2.0.0
      - adjusttext==0.7.3
      - aiofiles==23.2.1
      - altair==5.1.2
      - altgraph==0.17.4
      - annotated-types==0.6.0
      - anyio==3.7.1
      - astunparse==1.6.3
      - attrs==23.1.0
      - beautifulsoup4==4.12.2
      - cachetools==5.3.2
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - deprecated==1.2.14
      - exceptiongroup==1.2.0
      - fastapi==0.104.1
      - ffmpy==0.3.1
      - filelock==3.13.1
      - flatbuffers==23.5.26
      - fonttools==4.45.0
      - fsspec==2023.10.0
      - gast==0.4.0
      - gensim==4.3.2
      - google-auth==2.23.4
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - gradio==4.1.2
      - gradio-client==0.7.0
      - greenlet==3.0.3
      - grpcio==1.59.3
      - h11==0.14.0
      - h5py==3.10.0
      - hnswlib==0.6.2
      - httpcore==1.0.2
      - httptools==0.6.1
      - httpx==0.25.1
      - huggingface-hub==0.19.4
      - idna==3.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.1
      - jax==0.4.13
      - jinja2==3.1.2
      - joblib==1.3.2
      - jpype1==1.4.1
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.1
      - keras==2.11.0
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - llvmlite==0.40.1
      - lxml==4.9.3
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matchms==0.24.0
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - molmass==2023.4.10
      - ms2deepscore==0.2.3
      - networkx==3.1
      - numba==0.57.1
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - orjson==3.9.10
      - packaging==23.2
      - pandas==2.0.3
      - pickydict==0.4.0
      - pillow==10.1.0
      - pkgutil-resolve-name==1.3.10
      - protobuf==3.19.6
      - pubchempy==1.0.4
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydantic==2.5.1
      - pydantic-core==2.14.3
      - pydub==0.25.1
      - pygments==2.17.1
      - pyinstaller==5.5
      - pyinstaller-hooks-contrib==2023.10
      - pyparsing==3.1.1
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyteomics==4.6.3
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-multipart==0.0.6
      - pytz==2023.3.post1
      - pyyaml==6.0.2
      - rdkit==2023.9.5
      - rdkit-pypi==2022.9.5
      - referencing==0.31.0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.7.0
      - rpds-py==0.13.1
      - rsa==4.9
      - scikit-learn==1.1.3
      - scikit-opt==0.6.6
      - scipy==1.10.1
      - seaborn==0.13.0
      - semantic-version==2.10.0
      - setuptools==59.8.0
      - shellingham==1.5.4
      - six==1.16.0
      - smart-open==6.4.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - sparsestack==0.4.1
      - spec2vec==0.8.0
      - sqlalchemy==2.0.36
      - starlette==0.27.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.1
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - tomlkit==0.12.0
      - toolz==0.12.0
      - tqdm==4.66.1
      - typer==0.9.0
      - typing-extensions==4.8.0
      - tzdata==2024.1
      - urllib3==2.1.0
      - uvicorn==0.24.0.post1
      - watchfiles==0.21.0
      - websockets==11.0.3
      - werkzeug==3.0.1
      - wrapt==1.14.1
      - zipp==3.17.0